version: '3.0'

services:
  postgres:
    image: postgres:11
    restart: always
    env_file:
      - ./docker/postgres/docker-compose.dev.pg.env
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - united-water

  api:
    image: registry.citronium.com/united-water_api:${APP_VERSION:-latest}
    build: .
    restart: always
    environment:
      NODE_ENV: 'development'
    labels:
      - traefik.backend=united-water_api
      - traefik.frontend.rule=Host:unitedwater-api.psrv5.citronium.com
      - traefik.port=3000
      - traefik.docker.network=traefik_proxy
    networks:
      - united-water
      - traefik

networks:
  united-water:
    driver: bridge
  traefik:
    external:
      name: traefik_proxy

volumes:
  pg_data:
