version: '3.0'

services:
  postgres:
    image: postgres:11
    restart: always
    env_file:
      - ./docker/postgres/docker-compose.dev.pg.env
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - united-water

  api:
    image: registry.citronium.com/united-water_api:${APP_VERSION:-latest}
    build: .
    restart: always
    environment:
      NODE_ENV: 'development'
    labels:
      - traefik.backend=united-water_api
      - traefik.frontend.rule=Host:unitedwater-api.psrv5.citronium.com
      - traefik.port=3000
      - traefik.docker.network=traefik_proxy
    networks:
      - united-water
      - traefik

  syslog-ng:
    image: balabit/syslog-ng:3.36.1
    container_name: united-water_syslog-ng
    restart: always    
    volumes:
      - syslog_logs:/var/log
      - syslog_socket:/var/run/syslog-ng
      - syslog_config:/etc/syslog-ng
    ports:      
      - "514:514/udp"
    networks:      
      - united-water
networks:
  united-water:
    driver: bridge
  traefik:
    external:
      name: traefik_proxy

volumes:
  pg_data:
  syslog_logs:
  syslog_socket:
  syslog_config:
