version: '3.0'

services:
  postgres:
    image: postgres:11
    restart: always
    env_file:
      - ./docker/postgres/docker-compose.dev.pg.env
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - united-water

  api:
    image: registry.citronium.com/united-water_api:${APP_VERSION:-latest}
    build: .
    restart: always
    environment:
      NODE_ENV: 'development'
    labels:
      - traefik.backend=united-water_api
      - traefik.frontend.rule=Host:unitedwater-api.psrv5.citronium.com
      - traefik.port=3000
      - traefik.docker.network=traefik_proxy
    networks:
      - united-water
      - traefik

  syslog-ng:
    image: balabit/syslog-ng:3.36.1
    container_name: united-water_syslog-ng
    restart: always
    volumes:
      - syslog_logs:/var/log/syslog-ng
      - syslog_socket:/var/run/syslog-ng
      - syslog_config:/etc/syslog-ng
    ports:
      - '514:514/udp'
      - '601:601'
    networks:
      - united-water

  rabbitmq:
    image: rabbitmq:3.9-management-alpine
    container_name: 'rabbitmq'
    environment:
      - RABBITMQ_DEFAULT_USER=united_rabbit
      - RABBITMQ_DEFAULT_PASS=5lIHHO5QcvdSi
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbit_date:/var/lib/rabbitmq/
      - rabbit_logs:/var/log/rabbitmq
    networks:
      - united-water

  openssh-server:
    image: linuxserver/openssh-server
    container_name: united-water_ssh
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Moscow
      - SUDO_ACCESS=false #optional
      - PASSWORD_ACCESS=true #optional
      - USER_PASSWORD=GUTD78ymF3PbVe #optional
      - USER_NAME=unitedsshuser #optional
    volumes:
      - ssh_config:/config
      - syslog_logs:/var/log/syslog_ng
    ports:
      - 25225:2222
    restart: unless-stopped

  grafana:
    container_name: grafana_uw
    environment:
      GF_SECURITY_ADMIN_PASSWORD: "jV8mj4Z9T3RH63"
      GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH: /var/lib/grafana/dashboards/no_folder/loki_syslog_aio_overview.json
    image: grafana/grafana:8.1.2
    ports:
      - 25226:3000
    networks:
      - united-water   
    volumes:
    - grafana_provisioning:/etc/grafana/provisioning    
    - grafana_lib:/var/lib/grafana
    
  loki:
    command: -config.file=/etc/loki/loki-config.yml
    container_name: loki
    image: grafana/loki:2.3.0
    networks:
      - united-water
    volumes:
    - loki-config:/etc/loki
    
  promtail:
    command: -config.file=/etc/promtail/promtail-config.yml
    container_name: promtail_uw
    image: grafana/promtail:2.3.0
    networks:
      - united-water
    volumes:
    - promtail-config:/etc/promtail
    
  telegraf:
    image: telegraf:1.18-alpine
    volumes:
    - ./telegraf/etc/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    depends_on:
      - influxdb
    networks:
      - united-water
      
  influxdb:
    image: influxdb:1.8-alpine
    env_file: configuration.env
    networks:
      - united-water
    volumes:
      - ./:/imports
      - influxdb_data:/var/lib/influxdb

networks:
  united-water:
    driver: bridge
  traefik:
    external:
      name: traefik_proxy   

volumes:
  pg_data:
  syslog_logs:
  syslog_socket:
  syslog_config:
  ssh_config:
  rabbit_date:
  rabbit_logs:
  grafana_provisioning:
  grafana_lib:
  loki-config:
  promtail-config:
  influxdb_data:
