version: '3.0'

services:
  postgres:
    image: postgres:11
    restart: always
    env_file:
      - ./docker/postgres/docker-compose.dev.pg.env
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - united-water

  api:
    image: registry.citronium.com/united-water_api:${APP_VERSION:-latest}
    build: .
    restart: always
    environment:
      NODE_ENV: 'development'
    labels:
      - traefik.backend=united-water_api
      - traefik.frontend.rule=Host:unitedwater-api.psrv5.citronium.com
      - traefik.port=3000
      - traefik.docker.network=traefik_proxy
    networks:
      - united-water
      - traefik

  syslog-ng:
    image: balabit/syslog-ng:3.36.1
    container_name: united-water_syslog-ng
    restart: always
    volumes:
      - syslog_logs:/var/log/syslog-ng
      - syslog_socket:/var/run/syslog-ng
      - syslog_config:/etc/syslog-ng
    ports:
      - '514:514/udp'
      - '601:601'
    networks:
      - united-water

  rabbitmq:
    image: rabbitmq:3.9-management-alpine
    container_name: 'rabbitmq'
    environment:
      - RABBITMQ_DEFAULT_USER=united_rabbit
      - RABBITMQ_DEFAULT_PASS=5lIHHO5QcvdSi
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbit_date:/var/lib/rabbitmq/
      - rabbit_logs:/var/log/rabbitmq
    networks:
      - united-water

  openssh-server:
    image: linuxserver/openssh-server
    container_name: united-water_ssh
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Moscow
      - SUDO_ACCESS=false #optional
      - PASSWORD_ACCESS=true #optional
      - USER_PASSWORD=GUTD78ymF3PbVe #optional
      - USER_NAME=unitedsshuser #optional
    volumes:
      - ssh_config:/config
      - syslog_logs:/var/log/syslog_ng
    ports:
      - 25225:2222
    restart: unless-stopped

networks:
  united-water:
    driver: bridge
  traefik:
    external:
      name: traefik_proxy

volumes:
  pg_data:
  syslog_logs:
  syslog_socket:
  syslog_config:
  ssh_config:
  rabbit_date:
  rabbit_logs:
